# https://github.com/actions/stale
# https://docs.github.com/en/actions/managing-issues-and-pull-requests/closing-inactive-issues
name: Close Stale Issues
on:
  schedule:
    - cron: "30 * * * *"
#   - cron: "30 1 * * *"
#   - cron: "30 1,13 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 11
          days-before-issue-close: 5
          stale-issue-label: "stale"
#         stale-issue-message: "This issue is stale because it has been open for 12 days with no activity."
#         close-issue-message: "This issue was closed because it has been inactive for 5 days since being marked as stale."
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs. Thank you
            for your contributions.
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          exempt-issue-labels: pinned, security, enhancement
